# Generated by Django 2.1.3 on 2018-12-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upsdowns',
            old_name='down',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='upsdowns',
            old_name='up',
            new_name='val',
        ),
    ]
