# Generated by Django 2.1.3 on 2018-12-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=50)),
                ('track', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('sprint', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('devStories', models.IntegerField()),
                ('devStoryPoints', models.IntegerField()),
                ('devCommits', models.IntegerField()),
                ('qaStories', models.IntegerField()),
                ('qaStoryPoints', models.IntegerField()),
                ('qaCommits', models.IntegerField()),
            ],
        ),
    ]
