# Generated by Django 2.1.3 on 2018-12-10 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_auto_20181203_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='userName',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='metrics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pm.Users'),
        ),
    ]
