# Generated by Django 2.1.3 on 2018-12-11 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0003_auto_20181210_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.Users'),
        ),
    ]
