# Generated by Django 2.1.3 on 2018-12-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0004_auto_20181211_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='sprint',
            field=models.IntegerField(max_length=100),
        ),
    ]
