# Generated by Django 2.1.3 on 2018-12-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0005_auto_20181213_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='sprint',
            field=models.IntegerField(),
        ),
    ]
